### ISSUE TITLE
turn it into an async stream so it can handle back pressure?

### ISSUE THREAD

**Issue by laggingreflex** [seangenabe/stream-to-iterator#6]
Hey there, I just found this out and really liked it and [posted it on reddit](https://www.reddit.com/r/node/comments/69lyh6/streamtoiterator_converts_a_nodejs_stream_into_an/) where it's gotten a comment saying:

>You want to turn it into an [async stream](https://github.com/calvinmetcalf/async-iter-stream) so it can handle back pressure.

Hope that's useful.

**Comment by seangenabe** [comment]
Oh, yeah, I made this module before I had any knowledge of async iterators, which is basically the next step ahead of iterators and async.

This module is already supposed to be able to do async, following the return signature `Promise<Iterator<Promise>>` - you'll have to wait for the promise to resolve before getting the next one.

Also, I don't see how implementing `[Symbol.asyncIterator]()` would be able to handle back pressure, unless the mentioned module has already done so.

As for the main issue, back pressure, yes, my module does not implement back pressure, but I think this could be easily solved by piping the source stream to a `PassThrough` stream...? Eh, I don't know, I'm not very much of a streams guru. If anyone still wants back pressure on this module, I'll gladly implement it but I won't know how to test it. (Or any idea how to implement it actually except for what I mentioned.)

And finally, `Symbol.asyncIterator` is just a proposal yet. It hasn't landed on any major platforms including node.js. I'd gladly add that functionality (or make a new module even) when it lands.

PS: I think the mentioned module is already a competitor to that. Dang. Just use it then. Leave me alone crying in my corner.
